# vim: ft=dockerfile
FROM python:3.12

ARG USER_ID
ARG GROUP_ID
ARG USER_NAME

RUN useradd -u ${USER_ID} --create-home ${USER_NAME}

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    POETRY_VERSION=1.6.1 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_CREATE=false

# Install poetry with specific version
RUN curl -sSL https://install.python-poetry.org | \
    POETRY_VERSION=2.1.1 \
    python3 - && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN poetry install --no-root --no-interaction --no-ansi

COPY . .

USER ${USER_ID}:${GROUP_ID}
